In [59]:
# Imports dependencies

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint

#  Imports and reads the charity_data.csv

import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [60]:
# Drops the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df = application_df.drop(columns = ['EIN'])

application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [61]:
# Looks at APPLICATION_TYPE value counts to identify and replaces with "Other"

application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [62]:
# Creates a list of application types to be replaced

application_types_to_replace = ['T9','T13','T12','T2','T25','T14','T29','T15','T17']

# Replaces in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Checks to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [63]:
# Looks at CLASSIFICATION values counts greater than 1

class_count = application_df['CLASSIFICATION'].value_counts()

filtered_counts = class_count[class_count > 1]

filtered_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [64]:
# Creates list of classifications to be replaced based on cutoff point

classifications_to_replace = class_count[class_count < 1883].index

# Replaces in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Checks to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [65]:
name_count = application_df['NAME'].value_counts()

# Creates list of names to be replaced based on cutoff point

names_to_replace = name_count[name_count <= 6].index

# Replaces in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Checks to make sure replacement was successful
application_df['NAME'].value_counts()

NAME
Other                                          20277
PARENT BOOSTER USA INC                          1260
TOPS CLUB INC                                    765
UNITED STATES BOWLING CONGRESS INC               700
WASHINGTON STATE UNIVERSITY                      492
                                               ...
RCI INC                                            7
MYTEAM TRIUMPH INC                                 7
NATIONAL ASSOCIATION OF CORPORATE DIRECTORS        7
CHRISTIAN MEDICAL & DENTAL SOCIETY                 7
NATIONAL KAPPA KAPPA IOTA INC                      7
Name: count, Length: 316, dtype: int64

In [66]:
# Converts categorical data to numeric with `pd.get_dummies`

categories = pd.get_dummies(application_df)

categories = categories.astype(int)

categories.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [67]:
# Splits our preprocessed data into our features and target arrays

features_array = categories.drop(columns = ['IS_SUCCESSFUL'])

target_array = categories['IS_SUCCESSFUL']

# Splits the preprocessed data into a training and testing dataset

X_train, X_test, y_train, y_test = train_test_split(features_array, target_array, random_state = 24)

In [68]:
# Creates a StandardScaler instance

scaler = StandardScaler()

# Fits the StandardScaler

X_scaler = scaler.fit(X_train)

# Scales the data

X_train_scaled = X_scaler.transform(X_train)

X_test_scaled = X_scaler.transform(X_test)

In [69]:
# First Optimization Model


input_features = len(X_train_scaled[0])

hidden_nodes_layer_1 = 100

hidden_nodes_layer_2 = 80

hidden_nodes_layer_3 = 60

nn1 = tf.keras.models.Sequential()

# First hidden layer

nn1.add(tf.keras.layers.Dense(units = hidden_nodes_layer_1, input_dim = input_features, activation = 'relu'))

# Second hidden layer

nn1.add(tf.keras.layers.Dense(units = hidden_nodes_layer_2, activation = 'sigmoid'))

# Third hidden layer

nn1.add(tf.keras.layers.Dense(units = hidden_nodes_layer_3, activation = 'sigmoid'))

# Output layer

nn1.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Checks the structure of the model
nn1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 100)               36000

 dense_5 (Dense)             (None, 80)                8080

 dense_6 (Dense)             (None, 60)                4860

 dense_7 (Dense)             (None, 1)                 61

=================================================================
Total params: 49001 (191.41 KB)
Trainable params: 49001 (191.41 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [70]:
# Compiles the model

nn1.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [71]:
# Trains the model

fitted_model_1 = nn1.fit(X_train_scaled, y_train, epochs = 125)

Epoch 1/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4807 - accuracy: 0.7673
Epoch 2/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4396 - accuracy: 0.7896
Epoch 3/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4352 - accuracy: 0.7911
Epoch 4/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4325 - accuracy: 0.7933
Epoch 5/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4310 - accuracy: 0.7915
Epoch 6/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4281 - accuracy: 0.7946
Epoch 7/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4276 - accuracy: 0.7933
Epoch 8/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4258 - accuracy: 0.7950
Epoch 9/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4256 - accuracy: 0.7961
Epoch 10/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4244 - accuracy: 0.7945
Epoch 11/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4236 - accuracy: 0.7953
Epoch 12/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4231 - accuracy: 0.7956
Epoch 13/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4223 - accuracy: 0.7966
Epoch 14/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4218 - accuracy: 0.7962
Epoch 15/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4212 - accuracy: 0.7961
Epoch 16/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4208 - accuracy: 0.7979
Epoch 17/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4199 - accuracy: 0.7971
Epoch 18/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4191 - accuracy: 0.7976
Epoch 19/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4192 - accuracy: 0.7974
Epoch 20/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4191 - accuracy: 0.7972
Epoch 21/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4179 - accuracy: 0.7992
Epoch 22/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4170 - accuracy: 0.7999
Epoch 23/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4171 - accuracy: 0.7985
Epoch 24/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4164 - accuracy: 0.7996
Epoch 25/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4157 - accuracy: 0.7998
Epoch 26/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4157 - accuracy: 0.8013
Epoch 27/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4151 - accuracy: 0.7999
Epoch 28/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4146 - accuracy: 0.7996
Epoch 29/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4143 - accuracy: 0.8005
Epoch 30/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4143 - accuracy: 0.8003
Epoch 31/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4135 - accuracy: 0.8004
Epoch 32/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4135 - accuracy: 0.8016
Epoch 33/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4128 - accuracy: 0.8018
Epoch 34/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4121 - accuracy: 0.8006
Epoch 35/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4124 - accuracy: 0.8012
Epoch 36/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4115 - accuracy: 0.8014
Epoch 37/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4110 - accuracy: 0.8025
Epoch 38/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4108 - accuracy: 0.8013
Epoch 39/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4103 - accuracy: 0.8030
Epoch 40/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4101 - accuracy: 0.8020
Epoch 41/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4100 - accuracy: 0.8018
Epoch 42/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4103 - accuracy: 0.8024
Epoch 43/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4093 - accuracy: 0.8032
Epoch 44/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4092 - accuracy: 0.8022
Epoch 45/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4091 - accuracy: 0.8020
Epoch 46/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4090 - accuracy: 0.8029
Epoch 47/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4085 - accuracy: 0.8041
Epoch 48/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4087 - accuracy: 0.8032
Epoch 49/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4080 - accuracy: 0.8035
Epoch 50/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4079 - accuracy: 0.8035
Epoch 51/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4075 - accuracy: 0.8035
Epoch 52/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4074 - accuracy: 0.8045
Epoch 53/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4074 - accuracy: 0.8042
Epoch 54/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4068 - accuracy: 0.8040
Epoch 55/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4071 - accuracy: 0.8040
Epoch 56/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4068 - accuracy: 0.8040
Epoch 57/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4071 - accuracy: 0.8044
Epoch 58/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4068 - accuracy: 0.8041
Epoch 59/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4064 - accuracy: 0.8031
Epoch 60/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4064 - accuracy: 0.8034
Epoch 61/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4062 - accuracy: 0.8042
Epoch 62/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4059 - accuracy: 0.8045
Epoch 63/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4058 - accuracy: 0.8054
Epoch 64/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4059 - accuracy: 0.8041
Epoch 65/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4056 - accuracy: 0.8049
Epoch 66/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4053 - accuracy: 0.8044
Epoch 67/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4052 - accuracy: 0.8043
Epoch 68/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4055 - accuracy: 0.8053
Epoch 69/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4049 - accuracy: 0.8046
Epoch 70/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4051 - accuracy: 0.8045
Epoch 71/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4051 - accuracy: 0.8045
Epoch 72/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4051 - accuracy: 0.8061
Epoch 73/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4044 - accuracy: 0.8060
Epoch 74/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4049 - accuracy: 0.8052
Epoch 75/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8049
Epoch 76/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4044 - accuracy: 0.8050
Epoch 77/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4041 - accuracy: 0.8057
Epoch 78/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4047 - accuracy: 0.8058
Epoch 79/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4046 - accuracy: 0.8052
Epoch 80/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4040 - accuracy: 0.8053
Epoch 81/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4045 - accuracy: 0.8045
Epoch 82/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8050
Epoch 83/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4039 - accuracy: 0.8053
Epoch 84/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4037 - accuracy: 0.8057
Epoch 85/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4039 - accuracy: 0.8054
Epoch 86/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8054
Epoch 87/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4042 - accuracy: 0.8055
Epoch 88/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4039 - accuracy: 0.8056
Epoch 89/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8059
Epoch 90/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4034 - accuracy: 0.8058
Epoch 91/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8055
Epoch 92/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8054
Epoch 93/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8057
Epoch 94/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4032 - accuracy: 0.8054
Epoch 95/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4038 - accuracy: 0.8059
Epoch 96/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8054
Epoch 97/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8056
Epoch 98/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8059
Epoch 99/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8061
Epoch 100/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8060
Epoch 101/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4031 - accuracy: 0.8058
Epoch 102/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4032 - accuracy: 0.8066
Epoch 103/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8063
Epoch 104/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8075
Epoch 105/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8050
Epoch 106/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8063
Epoch 107/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4030 - accuracy: 0.8061
Epoch 108/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4028 - accuracy: 0.8059
Epoch 109/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4031 - accuracy: 0.8068
Epoch 110/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4026 - accuracy: 0.8059
Epoch 111/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4026 - accuracy: 0.8059
Epoch 112/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8072
Epoch 113/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8056
Epoch 114/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8068
Epoch 115/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8070
Epoch 116/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4027 - accuracy: 0.8056
Epoch 117/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4027 - accuracy: 0.8064
Epoch 118/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4026 - accuracy: 0.8060
Epoch 119/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8057
Epoch 120/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4027 - accuracy: 0.8068
Epoch 121/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8060
Epoch 122/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4030 - accuracy: 0.8059
Epoch 123/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4024 - accuracy: 0.8061
Epoch 124/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4031 - accuracy: 0.8067
Epoch 125/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4030 - accuracy: 0.8060

In [72]:
# Evaluates the first model using the test data

model_loss, model_accuracy = nn1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4721 - accuracy: 0.7873 - 457ms/epoch - 2ms/step
Loss: 0.47207212448120117, Accuracy: 0.7872886061668396

In [73]:
# Exports our model to HDF5 file

nn1.save('Alphabet_Soup_Charity_Optimization_Model_1.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(