In [1]:
# Imports dependencies

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint

#  Imports and reads the charity_data.csv

import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drops the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df = application_df.drop(columns = ['EIN'])

application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Looks at APPLICATION_TYPE value counts to identify and replaces with "Other"

application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [4]:
# Creates a list of application types to be replaced

application_types_to_replace = ['T9','T13','T12','T2','T25','T14','T29','T15','T17']

# Replaces in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Checks to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [5]:
# Looks at CLASSIFICATION value counts to identify and replace with "Other"

application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [6]:
# Creates list of classifications to be replaced based on cutoff point

class_count = application_df['CLASSIFICATION'].value_counts()

classifications_to_replace = class_count[class_count < 1883].index

# Replaces in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Checks to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [7]:
# Creates list of classifications to be replaced based on cutoff point

name_count = application_df['NAME'].value_counts()

names_to_replace = name_count[name_count <= 6].index

# Replaces in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name, "Other")


#Checks to make sure replacement was successful

application_df['NAME'].value_counts()

NAME
Other                                          20277
PARENT BOOSTER USA INC                          1260
TOPS CLUB INC                                    765
UNITED STATES BOWLING CONGRESS INC               700
WASHINGTON STATE UNIVERSITY                      492
                                               ...
RCI INC                                            7
MYTEAM TRIUMPH INC                                 7
NATIONAL ASSOCIATION OF CORPORATE DIRECTORS        7
CHRISTIAN MEDICAL & DENTAL SOCIETY                 7
NATIONAL KAPPA KAPPA IOTA INC                      7
Name: count, Length: 316, dtype: int64

In [8]:
# Converts categorical data to numeric with `pd.get_dummies`

categories = pd.get_dummies(application_df)

categories.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [9]:
# Splits our preprocessed data into our features and target arrays

features_array = categories.drop(columns = ['IS_SUCCESSFUL'])

target_array = categories['IS_SUCCESSFUL']

# Splits the preprocessed data into a training and testing dataset

X_train, X_test, y_train, y_test = train_test_split(features_array, target_array, random_state = 24)

In [10]:
# Creates a StandardScaler instance

scaler = StandardScaler()

# Fits the StandardScaler

X_scaler = scaler.fit(X_train)

# Scales the data

X_train_scaled = X_scaler.transform(X_train)

X_test_scaled = X_scaler.transform(X_test)

In [12]:
# Defines the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

input_features = len(X_train_scaled[0])

hidden_nodes_layer_1 = 100

hidden_nodes_layer_2 = 80

hidden_nodes_layer_3 = 60


nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer_1, input_dim = input_features, activation = 'relu'))

# Second hidden layer

nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer_2, activation = 'sigmoid'))

# Third hidden layer

nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer_3, activation = 'sigmoid'))


# Output layer

nn.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               36000

 dense_1 (Dense)             (None, 80)                8080

 dense_2 (Dense)             (None, 60)                4860

 dense_3 (Dense)             (None, 1)                 61

=================================================================
Total params: 49001 (191.41 KB)
Trainable params: 49001 (191.41 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compiles the model

nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [14]:
# Trains the model

fitted_model = nn.fit(X_train_scaled, y_train, epochs = 125)

Epoch 1/125
804/804 [==============================] - 6s 3ms/step - loss: 0.4782 - accuracy: 0.7714
Epoch 2/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4409 - accuracy: 0.7885
Epoch 3/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4343 - accuracy: 0.7913
Epoch 4/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4322 - accuracy: 0.7926
Epoch 5/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4301 - accuracy: 0.7918
Epoch 6/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4284 - accuracy: 0.7938
Epoch 7/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4277 - accuracy: 0.7947
Epoch 8/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4261 - accuracy: 0.7948
Epoch 9/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4255 - accuracy: 0.7949
Epoch 10/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4243 - accuracy: 0.7972
Epoch 11/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4230 - accuracy: 0.7967
Epoch 12/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4229 - accuracy: 0.7975
Epoch 13/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4223 - accuracy: 0.7950
Epoch 14/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4213 - accuracy: 0.7963
Epoch 15/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4208 - accuracy: 0.7978
Epoch 16/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4202 - accuracy: 0.7971
Epoch 17/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4196 - accuracy: 0.7975
Epoch 18/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4191 - accuracy: 0.7975
Epoch 19/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4186 - accuracy: 0.7980
Epoch 20/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4178 - accuracy: 0.7990
Epoch 21/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4170 - accuracy: 0.7993
Epoch 22/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4170 - accuracy: 0.7988
Epoch 23/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4165 - accuracy: 0.8000
Epoch 24/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4161 - accuracy: 0.7999
Epoch 25/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4159 - accuracy: 0.7996
Epoch 26/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4154 - accuracy: 0.7993
Epoch 27/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4149 - accuracy: 0.8012
Epoch 28/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4143 - accuracy: 0.8008
Epoch 29/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4140 - accuracy: 0.8019
Epoch 30/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4133 - accuracy: 0.8017
Epoch 31/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4135 - accuracy: 0.8015
Epoch 32/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4130 - accuracy: 0.8016
Epoch 33/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4125 - accuracy: 0.8019
Epoch 34/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4127 - accuracy: 0.8018
Epoch 35/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4121 - accuracy: 0.8015
Epoch 36/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4118 - accuracy: 0.8024
Epoch 37/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4118 - accuracy: 0.8021
Epoch 38/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4110 - accuracy: 0.8022
Epoch 39/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4107 - accuracy: 0.8030
Epoch 40/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4103 - accuracy: 0.8036
Epoch 41/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4106 - accuracy: 0.8031
Epoch 42/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4101 - accuracy: 0.8025
Epoch 43/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4098 - accuracy: 0.8027
Epoch 44/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4097 - accuracy: 0.8037
Epoch 45/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4091 - accuracy: 0.8025
Epoch 46/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4093 - accuracy: 0.8029
Epoch 47/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4091 - accuracy: 0.8020
Epoch 48/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4087 - accuracy: 0.8028
Epoch 49/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4087 - accuracy: 0.8031
Epoch 50/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4087 - accuracy: 0.8034
Epoch 51/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4084 - accuracy: 0.8035
Epoch 52/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4080 - accuracy: 0.8040
Epoch 53/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4077 - accuracy: 0.8038
Epoch 54/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4080 - accuracy: 0.8034
Epoch 55/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4075 - accuracy: 0.8042
Epoch 56/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4071 - accuracy: 0.8045
Epoch 57/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4076 - accuracy: 0.8037
Epoch 58/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4071 - accuracy: 0.8042
Epoch 59/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4069 - accuracy: 0.8046
Epoch 60/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4069 - accuracy: 0.8050
Epoch 61/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4060 - accuracy: 0.8045
Epoch 62/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4069 - accuracy: 0.8046
Epoch 63/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4062 - accuracy: 0.8044
Epoch 64/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4062 - accuracy: 0.8048
Epoch 65/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4057 - accuracy: 0.8044
Epoch 66/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4058 - accuracy: 0.8038
Epoch 67/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4057 - accuracy: 0.8043
Epoch 68/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4053 - accuracy: 0.8042
Epoch 69/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4053 - accuracy: 0.8042
Epoch 70/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4059 - accuracy: 0.8037
Epoch 71/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4053 - accuracy: 0.8053
Epoch 72/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4053 - accuracy: 0.8050
Epoch 73/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4049 - accuracy: 0.8052
Epoch 74/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4054 - accuracy: 0.8042
Epoch 75/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4049 - accuracy: 0.8045
Epoch 76/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4057 - accuracy: 0.8033
Epoch 77/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4050 - accuracy: 0.8046
Epoch 78/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4046 - accuracy: 0.8051
Epoch 79/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4045 - accuracy: 0.8050
Epoch 80/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4043 - accuracy: 0.8047
Epoch 81/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4047 - accuracy: 0.8057
Epoch 82/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8053
Epoch 83/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8049
Epoch 84/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4041 - accuracy: 0.8048
Epoch 85/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4039 - accuracy: 0.8052
Epoch 86/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4042 - accuracy: 0.8051
Epoch 87/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4038 - accuracy: 0.8051
Epoch 88/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4037 - accuracy: 0.8058
Epoch 89/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8055
Epoch 90/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4035 - accuracy: 0.8055
Epoch 91/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4036 - accuracy: 0.8056
Epoch 92/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4033 - accuracy: 0.8052
Epoch 93/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4034 - accuracy: 0.8047
Epoch 94/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4032 - accuracy: 0.8049
Epoch 95/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4035 - accuracy: 0.8048
Epoch 96/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4031 - accuracy: 0.8057
Epoch 97/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4034 - accuracy: 0.8055
Epoch 98/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4032 - accuracy: 0.8051
Epoch 99/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4039 - accuracy: 0.8053
Epoch 100/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4035 - accuracy: 0.8054
Epoch 101/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4032 - accuracy: 0.8057
Epoch 102/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4033 - accuracy: 0.8056
Epoch 103/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4035 - accuracy: 0.8056
Epoch 104/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4033 - accuracy: 0.8057
Epoch 105/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8056
Epoch 106/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4043 - accuracy: 0.8055
Epoch 107/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4035 - accuracy: 0.8055
Epoch 108/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4033 - accuracy: 0.8057
Epoch 109/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8061
Epoch 110/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4033 - accuracy: 0.8060
Epoch 111/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4036 - accuracy: 0.8061
Epoch 112/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4034 - accuracy: 0.8063
Epoch 113/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8057
Epoch 114/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4029 - accuracy: 0.8061
Epoch 115/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4033 - accuracy: 0.8058
Epoch 116/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4027 - accuracy: 0.8059
Epoch 117/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4030 - accuracy: 0.8057
Epoch 118/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4044 - accuracy: 0.8054
Epoch 119/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4035 - accuracy: 0.8059
Epoch 120/125
804/804 [==============================] - 3s 4ms/step - loss: 0.4029 - accuracy: 0.8063
Epoch 121/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4032 - accuracy: 0.8058
Epoch 122/125
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8062
Epoch 123/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8059
Epoch 124/125
804/804 [==============================] - 2s 3ms/step - loss: 0.4033 - accuracy: 0.8066
Epoch 125/125
804/804 [==============================] - 3s 3ms/step - loss: 0.4035 - accuracy: 0.8066

In [15]:
# Evaluates the model using the test data

model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4670 - accuracy: 0.7910 - 506ms/epoch - 2ms/step
Loss: 0.46699240803718567, Accuracy: 0.791020393371582

In [16]:
# Exports model to HDF5 file

nn.save('Alphabet_Soup_Charity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(